import Image from "next/image";
import Head from 'next/head'
import Contact from "./contact";
import Nav1 from "@/components/Nav1";
import Footer from "@/components/Footer";


export default function Home() {
  return (
   
  <>
  <Head>

        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
     <title>Contact us</title>
       
          

          

      </Head>
  <div className='overflow-hidden'>
   
<Nav1/>
 <Contact/>
 <Footer/>
 



  </div>

  
  </>
  );
}
