import Image from "next/image";
import Head from 'next/head'
import Signup from './signup'


export default function Home() {
  return (
   
  <>
  <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
     <title>Sign up</title>
       
          

          

      </Head>
  <div className='overflow-hidden'>
   

 <Signup/>
 



  </div>

  
  </>
  );
}
