import Image from "next/image";
import Head from 'next/head'
import Foodlistdetails from "./Foodlistdetails"
import Nav1 from "@/components/Nav1";
import Footer from "@/components/Footer";
export default function Home() {
  return (
   
  <>
  <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
     <title>Menu Details</title>
       
          

          

      </Head>
  <div className='overflow-hidden'>
    <Nav1/>

<Foodlistdetails/>
<Footer/>


 
 



  </div>

  
  </>
  );
}
